[theme]
primaryColor = "#B22222"  # Vermelho Facility
backgroundColor = "#FFFFFF" # Fundo Branco
secondaryBackgroundColor = "#F0F2F6" # Cinza claro para menus e caixas
textColor = "#262730" # Texto escuro
font = "sans serif"